# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "yak_qv"
description: a tool to estimate base quality values from k-mer hash table and reads
keywords:
  - kmer
  - fastq
  - quality
  - qv
  - sequence

tools:
  - "yak":
      description: "Yet another k-mer analyzer"
      homepage: "https://github.com/lh3/yak"
      documentation: "https://github.com/lh3/yak/blob/master/README.md"
      tool_dev_url: "https://github.com/lh3/yak"
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - child_yak:
        type: file
        description: k-mer hash table file (.yak)
        pattern: "*.{yak}"
        ontologies: []
    - reads:
        type: file
        description: reads fastq/fasta file
        pattern: "*.{fastq.gz,fq.gz,fasta.gz,fa.gz,fastq,fq,fasta,fa}"
        ontologies: []

output:
  qv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.qv.txt":
          type: file
          description: quality value estimates for each read
          pattern: "*.{qv.txt}"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML

authors:
  - "@mpampuch"
maintainers:
  - "@mpampuch"
